"""Support for video url

Revision ID: 1af3a4170464
Revises: 44ec45984210
Create Date: 2018-11-04 15:59:24.473672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af3a4170464'
down_revision = '44ec45984210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('url', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'url')
    # ### end Alembic commands ###
